# ??
server:
  port: 9001

# Sa-Token ??
sa-token:
  # SSO-????
  sso-client:
    # SSO-Server?????
    server-url: http://sso.stp.com:9000

  # ?? Sa-Token ?????Redis?? ??????SSO-Server??????Redis?
  alone-redis:
    # Redis?????
    database: 2
    # Redis?????
    host: 127.0.0.1
    # Redis???????
    port: 6379
    # Redis?????????????
    password:
    # ??????
    timeout: 10s
